teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 20.0
    scale_linear_turbo:
      x: 40.0

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 100.0
    scale_angular_turbo:
      yaw: 200.0

    enable_button: 6           # LT (通常速度)
    enable_turbo_button: 4     # LB (ターボ)
    require_enable_button: false  # RB単独でもターボ有効
